spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.0.119/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://121.36.231.250/mysql?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#yml文档中配置日志，这种方式功能不够完整，logback-spring.xml可以完整配置企业应用日志
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: /var/log/tomcat/sell.log
#  level:

#项目路径
server:
  servlet:
    context-path: /sell
logging:
  level:
    com.star.dataobject.mapper: trace